//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MPMVC.ServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.SendSoap")]
    public interface SendSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendSimpleSMS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string[] SendSimpleSMS(string username, string password, string[] to, string from, string text, bool isflash);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendSimpleSMS", ReplyAction="*")]
        System.Threading.Tasks.Task<string[]> SendSimpleSMSAsync(string username, string password, string[] to, string from, string text, bool isflash);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendSimpleSMS2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SendSimpleSMS2(string username, string password, string to, string from, string text, bool isflash);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendSimpleSMS2", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SendSimpleSMS2Async(string username, string password, string to, string from, string text, bool isflash);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendSms", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        MPMVC.ServiceReference.SendSmsResponse SendSms(MPMVC.ServiceReference.SendSmsRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendSms", ReplyAction="*")]
        System.Threading.Tasks.Task<MPMVC.ServiceReference.SendSmsResponse> SendSmsAsync(MPMVC.ServiceReference.SendSmsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendWithDomain", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SendWithDomain(string username, string password, string to, string from, string text, bool isflash, string domainName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendWithDomain", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SendWithDomainAsync(string username, string password, string to, string from, string text, bool isflash, string domainName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSmsPrice", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        double GetSmsPrice(string username, string password, int irancellCount, int mtnCount, string from, string text);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSmsPrice", ReplyAction="*")]
        System.Threading.Tasks.Task<double> GetSmsPriceAsync(string username, string password, int irancellCount, int mtnCount, string from, string text);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCredit", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        double GetCredit(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCredit", ReplyAction="*")]
        System.Threading.Tasks.Task<double> GetCreditAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDelivery", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int GetDelivery(long recId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDelivery", ReplyAction="*")]
        System.Threading.Tasks.Task<int> GetDeliveryAsync(long recId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDelivery2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int GetDelivery2(string recId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDelivery2", ReplyAction="*")]
        System.Threading.Tasks.Task<int> GetDelivery2Async(string recId);
        
        // CODEGEN: Parameter 'GetMultiDeliveryResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMultiDelivery", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        MPMVC.ServiceReference.GetMultiDeliveryResponse GetMultiDelivery(MPMVC.ServiceReference.GetMultiDeliveryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMultiDelivery", ReplyAction="*")]
        System.Threading.Tasks.Task<MPMVC.ServiceReference.GetMultiDeliveryResponse> GetMultiDeliveryAsync(MPMVC.ServiceReference.GetMultiDeliveryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMultiDelivery2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string[] GetMultiDelivery2(string recId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMultiDelivery2", ReplyAction="*")]
        System.Threading.Tasks.Task<string[]> GetMultiDelivery2Async(string recId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDeliveries", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int[] GetDeliveries(long[] recIds, string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDeliveries", ReplyAction="*")]
        System.Threading.Tasks.Task<int[]> GetDeliveriesAsync(long[] recIds, string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDeliveries2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int GetDeliveries2(string recId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDeliveries2", ReplyAction="*")]
        System.Threading.Tasks.Task<int> GetDeliveries2Async(string recId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDeliveries3", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int[] GetDeliveries3(string[] recId, string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDeliveries3", ReplyAction="*")]
        System.Threading.Tasks.Task<int[]> GetDeliveries3Async(string[] recId, string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetInboxCount", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int GetInboxCount(string username, string password, bool isRead);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetInboxCount", ReplyAction="*")]
        System.Threading.Tasks.Task<int> GetInboxCountAsync(string username, string password, bool isRead);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getMessages", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseBL))]
        MPMVC.ServiceReference.MessagesBL[] getMessages(string username, string password, int location, string from, int index, int count);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getMessages", ReplyAction="*")]
        System.Threading.Tasks.Task<MPMVC.ServiceReference.MessagesBL[]> getMessagesAsync(string username, string password, int location, string from, int index, int count);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendByBaseNumber", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseBL))]
        string SendByBaseNumber(string username, string password, string[] text, string to, int bodyId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendByBaseNumber", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SendByBaseNumberAsync(string username, string password, string[] text, string to, int bodyId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendByBaseNumber2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseBL))]
        string SendByBaseNumber2(string username, string password, string text, string to, int bodyId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendByBaseNumber2", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SendByBaseNumber2Async(string username, string password, string text, string to, int bodyId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendByBaseNumber3", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseBL))]
        string SendByBaseNumber3(string username, string password, string text, string to);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendByBaseNumber3", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SendByBaseNumber3Async(string username, string password, string text, string to);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendSms", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SendSmsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string[] to;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string from;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string text;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public bool isflash;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public string udh;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=7)]
        public long[] recId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=8)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] status;
        
        public SendSmsRequest() {
        }
        
        public SendSmsRequest(string username, string password, string[] to, string from, string text, bool isflash, string udh, long[] recId, byte[] status) {
            this.username = username;
            this.password = password;
            this.to = to;
            this.from = from;
            this.text = text;
            this.isflash = isflash;
            this.udh = udh;
            this.recId = recId;
            this.status = status;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendSmsResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SendSmsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int SendSmsResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public long[] recId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] status;
        
        public SendSmsResponse() {
        }
        
        public SendSmsResponse(int SendSmsResult, long[] recId, byte[] status) {
            this.SendSmsResult = SendSmsResult;
            this.recId = recId;
            this.status = status;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetMultiDelivery", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetMultiDeliveryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string recId;
        
        public GetMultiDeliveryRequest() {
        }
        
        public GetMultiDeliveryRequest(string recId) {
            this.recId = recId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetMultiDeliveryResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetMultiDeliveryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] GetMultiDeliveryResult;
        
        public GetMultiDeliveryResponse() {
        }
        
        public GetMultiDeliveryResponse(byte[] GetMultiDeliveryResult) {
            this.GetMultiDeliveryResult = GetMultiDeliveryResult;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class MessagesBL : BaseBL {
        
        private long msgIDField;
        
        private int userIDField;
        
        private int linkIDField;
        
        private int numberIDField;
        
        private double tariffField;
        
        private byte msgTypeField;
        
        private string bodyField;
        
        private string udhField;
        
        private System.DateTime sendDateField;
        
        private string senderField;
        
        private string receiverField;
        
        private int firstLocationField;
        
        private int currentLocationField;
        
        private int partsField;
        
        private bool isFlashField;
        
        private bool isReadField;
        
        private bool isUnicodeField;
        
        private double creditField;
        
        private int moduleField;
        
        private int recCountField;
        
        private int recFailedField;
        
        private int recSuccessField;
        
        private bool isMoneyBackField;
        
        private int userStepedMasterField;
        
        private int userMasterField;
        
        private int moneyBackCountField;
        
        private int moneyBackLevelField;
        
        private System.Nullable<bool> autoSpeechTextField;
        
        private System.Nullable<int> shareServiceBodyIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long MsgID {
            get {
                return this.msgIDField;
            }
            set {
                this.msgIDField = value;
                this.RaisePropertyChanged("MsgID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int UserID {
            get {
                return this.userIDField;
            }
            set {
                this.userIDField = value;
                this.RaisePropertyChanged("UserID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int LinkID {
            get {
                return this.linkIDField;
            }
            set {
                this.linkIDField = value;
                this.RaisePropertyChanged("LinkID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int NumberID {
            get {
                return this.numberIDField;
            }
            set {
                this.numberIDField = value;
                this.RaisePropertyChanged("NumberID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public double Tariff {
            get {
                return this.tariffField;
            }
            set {
                this.tariffField = value;
                this.RaisePropertyChanged("Tariff");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public byte MsgType {
            get {
                return this.msgTypeField;
            }
            set {
                this.msgTypeField = value;
                this.RaisePropertyChanged("MsgType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Body {
            get {
                return this.bodyField;
            }
            set {
                this.bodyField = value;
                this.RaisePropertyChanged("Body");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Udh {
            get {
                return this.udhField;
            }
            set {
                this.udhField = value;
                this.RaisePropertyChanged("Udh");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public System.DateTime SendDate {
            get {
                return this.sendDateField;
            }
            set {
                this.sendDateField = value;
                this.RaisePropertyChanged("SendDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string Sender {
            get {
                return this.senderField;
            }
            set {
                this.senderField = value;
                this.RaisePropertyChanged("Sender");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Receiver {
            get {
                return this.receiverField;
            }
            set {
                this.receiverField = value;
                this.RaisePropertyChanged("Receiver");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public int FirstLocation {
            get {
                return this.firstLocationField;
            }
            set {
                this.firstLocationField = value;
                this.RaisePropertyChanged("FirstLocation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public int CurrentLocation {
            get {
                return this.currentLocationField;
            }
            set {
                this.currentLocationField = value;
                this.RaisePropertyChanged("CurrentLocation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public int Parts {
            get {
                return this.partsField;
            }
            set {
                this.partsField = value;
                this.RaisePropertyChanged("Parts");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public bool IsFlash {
            get {
                return this.isFlashField;
            }
            set {
                this.isFlashField = value;
                this.RaisePropertyChanged("IsFlash");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public bool IsRead {
            get {
                return this.isReadField;
            }
            set {
                this.isReadField = value;
                this.RaisePropertyChanged("IsRead");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public bool IsUnicode {
            get {
                return this.isUnicodeField;
            }
            set {
                this.isUnicodeField = value;
                this.RaisePropertyChanged("IsUnicode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public double Credit {
            get {
                return this.creditField;
            }
            set {
                this.creditField = value;
                this.RaisePropertyChanged("Credit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public int Module {
            get {
                return this.moduleField;
            }
            set {
                this.moduleField = value;
                this.RaisePropertyChanged("Module");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public int RecCount {
            get {
                return this.recCountField;
            }
            set {
                this.recCountField = value;
                this.RaisePropertyChanged("RecCount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public int RecFailed {
            get {
                return this.recFailedField;
            }
            set {
                this.recFailedField = value;
                this.RaisePropertyChanged("RecFailed");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public int RecSuccess {
            get {
                return this.recSuccessField;
            }
            set {
                this.recSuccessField = value;
                this.RaisePropertyChanged("RecSuccess");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public bool IsMoneyBack {
            get {
                return this.isMoneyBackField;
            }
            set {
                this.isMoneyBackField = value;
                this.RaisePropertyChanged("IsMoneyBack");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public int UserStepedMaster {
            get {
                return this.userStepedMasterField;
            }
            set {
                this.userStepedMasterField = value;
                this.RaisePropertyChanged("UserStepedMaster");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public int UserMaster {
            get {
                return this.userMasterField;
            }
            set {
                this.userMasterField = value;
                this.RaisePropertyChanged("UserMaster");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public int MoneyBackCount {
            get {
                return this.moneyBackCountField;
            }
            set {
                this.moneyBackCountField = value;
                this.RaisePropertyChanged("MoneyBackCount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public int MoneyBackLevel {
            get {
                return this.moneyBackLevelField;
            }
            set {
                this.moneyBackLevelField = value;
                this.RaisePropertyChanged("MoneyBackLevel");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=27)]
        public System.Nullable<bool> AutoSpeechText {
            get {
                return this.autoSpeechTextField;
            }
            set {
                this.autoSpeechTextField = value;
                this.RaisePropertyChanged("AutoSpeechText");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=28)]
        public System.Nullable<int> ShareServiceBodyID {
            get {
                return this.shareServiceBodyIDField;
            }
            set {
                this.shareServiceBodyIDField = value;
                this.RaisePropertyChanged("ShareServiceBodyID");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MessagesBL))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class BaseBL : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SendSoapChannel : MPMVC.ServiceReference.SendSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SendSoapClient : System.ServiceModel.ClientBase<MPMVC.ServiceReference.SendSoap>, MPMVC.ServiceReference.SendSoap {
        
        public SendSoapClient() {
        }
        
        public SendSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SendSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SendSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SendSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string[] SendSimpleSMS(string username, string password, string[] to, string from, string text, bool isflash) {
            return base.Channel.SendSimpleSMS(username, password, to, from, text, isflash);
        }
        
        public System.Threading.Tasks.Task<string[]> SendSimpleSMSAsync(string username, string password, string[] to, string from, string text, bool isflash) {
            return base.Channel.SendSimpleSMSAsync(username, password, to, from, text, isflash);
        }
        
        public string SendSimpleSMS2(string username, string password, string to, string from, string text, bool isflash) {
            return base.Channel.SendSimpleSMS2(username, password, to, from, text, isflash);
        }
        
        public System.Threading.Tasks.Task<string> SendSimpleSMS2Async(string username, string password, string to, string from, string text, bool isflash) {
            return base.Channel.SendSimpleSMS2Async(username, password, to, from, text, isflash);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MPMVC.ServiceReference.SendSmsResponse MPMVC.ServiceReference.SendSoap.SendSms(MPMVC.ServiceReference.SendSmsRequest request) {
            return base.Channel.SendSms(request);
        }
        
        public int SendSms(string username, string password, string[] to, string from, string text, bool isflash, string udh, ref long[] recId, ref byte[] status) {
            MPMVC.ServiceReference.SendSmsRequest inValue = new MPMVC.ServiceReference.SendSmsRequest();
            inValue.username = username;
            inValue.password = password;
            inValue.to = to;
            inValue.from = from;
            inValue.text = text;
            inValue.isflash = isflash;
            inValue.udh = udh;
            inValue.recId = recId;
            inValue.status = status;
            MPMVC.ServiceReference.SendSmsResponse retVal = ((MPMVC.ServiceReference.SendSoap)(this)).SendSms(inValue);
            recId = retVal.recId;
            status = retVal.status;
            return retVal.SendSmsResult;
        }
        
        public System.Threading.Tasks.Task<MPMVC.ServiceReference.SendSmsResponse> SendSmsAsync(MPMVC.ServiceReference.SendSmsRequest request) {
            return base.Channel.SendSmsAsync(request);
        }
        
        public string SendWithDomain(string username, string password, string to, string from, string text, bool isflash, string domainName) {
            return base.Channel.SendWithDomain(username, password, to, from, text, isflash, domainName);
        }
        
        public System.Threading.Tasks.Task<string> SendWithDomainAsync(string username, string password, string to, string from, string text, bool isflash, string domainName) {
            return base.Channel.SendWithDomainAsync(username, password, to, from, text, isflash, domainName);
        }
        
        public double GetSmsPrice(string username, string password, int irancellCount, int mtnCount, string from, string text) {
            return base.Channel.GetSmsPrice(username, password, irancellCount, mtnCount, from, text);
        }
        
        public System.Threading.Tasks.Task<double> GetSmsPriceAsync(string username, string password, int irancellCount, int mtnCount, string from, string text) {
            return base.Channel.GetSmsPriceAsync(username, password, irancellCount, mtnCount, from, text);
        }
        
        public double GetCredit(string username, string password) {
            return base.Channel.GetCredit(username, password);
        }
        
        public System.Threading.Tasks.Task<double> GetCreditAsync(string username, string password) {
            return base.Channel.GetCreditAsync(username, password);
        }
        
        public int GetDelivery(long recId) {
            return base.Channel.GetDelivery(recId);
        }
        
        public System.Threading.Tasks.Task<int> GetDeliveryAsync(long recId) {
            return base.Channel.GetDeliveryAsync(recId);
        }
        
        public int GetDelivery2(string recId) {
            return base.Channel.GetDelivery2(recId);
        }
        
        public System.Threading.Tasks.Task<int> GetDelivery2Async(string recId) {
            return base.Channel.GetDelivery2Async(recId);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MPMVC.ServiceReference.GetMultiDeliveryResponse MPMVC.ServiceReference.SendSoap.GetMultiDelivery(MPMVC.ServiceReference.GetMultiDeliveryRequest request) {
            return base.Channel.GetMultiDelivery(request);
        }
        
        public byte[] GetMultiDelivery(string recId) {
            MPMVC.ServiceReference.GetMultiDeliveryRequest inValue = new MPMVC.ServiceReference.GetMultiDeliveryRequest();
            inValue.recId = recId;
            MPMVC.ServiceReference.GetMultiDeliveryResponse retVal = ((MPMVC.ServiceReference.SendSoap)(this)).GetMultiDelivery(inValue);
            return retVal.GetMultiDeliveryResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MPMVC.ServiceReference.GetMultiDeliveryResponse> MPMVC.ServiceReference.SendSoap.GetMultiDeliveryAsync(MPMVC.ServiceReference.GetMultiDeliveryRequest request) {
            return base.Channel.GetMultiDeliveryAsync(request);
        }
        
        public System.Threading.Tasks.Task<MPMVC.ServiceReference.GetMultiDeliveryResponse> GetMultiDeliveryAsync(string recId) {
            MPMVC.ServiceReference.GetMultiDeliveryRequest inValue = new MPMVC.ServiceReference.GetMultiDeliveryRequest();
            inValue.recId = recId;
            return ((MPMVC.ServiceReference.SendSoap)(this)).GetMultiDeliveryAsync(inValue);
        }
        
        public string[] GetMultiDelivery2(string recId) {
            return base.Channel.GetMultiDelivery2(recId);
        }
        
        public System.Threading.Tasks.Task<string[]> GetMultiDelivery2Async(string recId) {
            return base.Channel.GetMultiDelivery2Async(recId);
        }
        
        public int[] GetDeliveries(long[] recIds, string username, string password) {
            return base.Channel.GetDeliveries(recIds, username, password);
        }
        
        public System.Threading.Tasks.Task<int[]> GetDeliveriesAsync(long[] recIds, string username, string password) {
            return base.Channel.GetDeliveriesAsync(recIds, username, password);
        }
        
        public int GetDeliveries2(string recId) {
            return base.Channel.GetDeliveries2(recId);
        }
        
        public System.Threading.Tasks.Task<int> GetDeliveries2Async(string recId) {
            return base.Channel.GetDeliveries2Async(recId);
        }
        
        public int[] GetDeliveries3(string[] recId, string username, string password) {
            return base.Channel.GetDeliveries3(recId, username, password);
        }
        
        public System.Threading.Tasks.Task<int[]> GetDeliveries3Async(string[] recId, string username, string password) {
            return base.Channel.GetDeliveries3Async(recId, username, password);
        }
        
        public int GetInboxCount(string username, string password, bool isRead) {
            return base.Channel.GetInboxCount(username, password, isRead);
        }
        
        public System.Threading.Tasks.Task<int> GetInboxCountAsync(string username, string password, bool isRead) {
            return base.Channel.GetInboxCountAsync(username, password, isRead);
        }
        
        public MPMVC.ServiceReference.MessagesBL[] getMessages(string username, string password, int location, string from, int index, int count) {
            return base.Channel.getMessages(username, password, location, from, index, count);
        }
        
        public System.Threading.Tasks.Task<MPMVC.ServiceReference.MessagesBL[]> getMessagesAsync(string username, string password, int location, string from, int index, int count) {
            return base.Channel.getMessagesAsync(username, password, location, from, index, count);
        }
        
        public string SendByBaseNumber(string username, string password, string[] text, string to, int bodyId) {
            return base.Channel.SendByBaseNumber(username, password, text, to, bodyId);
        }
        
        public System.Threading.Tasks.Task<string> SendByBaseNumberAsync(string username, string password, string[] text, string to, int bodyId) {
            return base.Channel.SendByBaseNumberAsync(username, password, text, to, bodyId);
        }
        
        public string SendByBaseNumber2(string username, string password, string text, string to, int bodyId) {
            return base.Channel.SendByBaseNumber2(username, password, text, to, bodyId);
        }
        
        public System.Threading.Tasks.Task<string> SendByBaseNumber2Async(string username, string password, string text, string to, int bodyId) {
            return base.Channel.SendByBaseNumber2Async(username, password, text, to, bodyId);
        }
        
        public string SendByBaseNumber3(string username, string password, string text, string to) {
            return base.Channel.SendByBaseNumber3(username, password, text, to);
        }
        
        public System.Threading.Tasks.Task<string> SendByBaseNumber3Async(string username, string password, string text, string to) {
            return base.Channel.SendByBaseNumber3Async(username, password, text, to);
        }
    }
}
